# minimal compose for a simulation inspiring on https://github.com/weaveworks/weaveDemo
version: '2'

services:
  front-end:
    image: kdop/go-generic-service:0.0.1
    container_name: front-end
    hostname: front-end
    environment:
      - SCHED_CALL_URL_LST=http://front-end:8000/s
      - SCHED_CALL_INTERVAL=5
      - SPLIT_CALL_URL_LST=http://login:8000/r?code=200&delay=1
      - APP=front-end
      - VERSION=v1

  login:
    image: kdop/go-generic-service:0.0.1
    container_name: login
    hostname: login
    environment:
      - APP=login
      - VERSION=v1

  # catalogue:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: catalogue
  # orders:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: orders
  #   environment:
  #     - SPLIT_CALL_URL_LST=http://shipping:8000/s,http://cart:8000/s,http://orders-db:8000/,http://payment:8000/,http://accounts:8000/s
  # orders-db:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: orders-db
  # shipping:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: shipping
  #   environment:
  #     - SPLIT_CALL_URL_LST=http://queue:8000/
  # queue:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: queue
  # cart:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: cart
  #   environment:
  #     - SPLIT_CALL_URL_LST=http://cart-db:8000/
  # cart-db:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: cart-db
  # payment:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: payment
  # accounts:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: accounts
  #   environment:
  #     - SPLIT_CALL_URL_LST=http://accounts-db:8000/
  # accounts-db:
  #   image: kdop/go-generic-service:0.0.1
  #   container_name: accounts-db
